typography_spectrum: 0.1523297
color:
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#BCBCBE'
    - '#4B4B4B'
    - '#A21621'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49579
analytics:
  google: null
  facebook: null
  twitter: null
name: HarvesterCharters.com
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e7cec02-0907-477b-b59b-f4d470637427.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Harvester Charters
purpose: []
