layout_spectrum: 1
color:
  saturation: 0.7199029
  lightness: 0.5766563
  brandStrength: 0.7258065
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#BCBCBE'
    - '#4B4B4B'
    - '#A21621'
  rhythmicContrast: 0.4725863
typography_spectrum: 0.3028674
name: HarvesterCharters.com
