name: HarvesterCharters.com
favicon: null
layout_spectrum: 0.24868
typography_spectrum: 0.1523297
title: Harvester Charters
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#BCBCBE'
    - '#4B4B4B'
    - '#A21621'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
