collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6129032
  brandStrength: 0.7258065
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#BCBCBE'
    - '#4B4B4B'
    - '#A21621'
  rhythmicContrast: 0.5483871
typography_spectrum: 0.09677419
layout_spectrum: 0.234767
name: HarvesterCharters.com
